@startuml inline_umlgraph_1.svg
class ArchiveConfig {}

ArchiveConfig --> Config

note right of ArchiveConfig
Responsibilities:
- Stores archive related configurations

Collaborators:
- Config
end note
@enduml
@startuml inline_umlgraph_2.svg
class AuditConfig {}

AuditConfig --> Config

note right of AuditConfig
Responsibilities:
- holds configuration related to the audit

Collaborators:
- Config
end note
@enduml
@startuml inline_umlgraph_3.svg
class BatchConfig {

}

BatchConfig --> Config

note right of BatchConfig
Responsibilities:
- Holds configurations related to the batch

Collaborators:
- Config
end note
@enduml
@startuml inline_umlgraph_4.svg
class ConditionConfig {
    + method()
}

ConditionConfig --> Config

note bottom of ConditionConfig
Responsibilities:
- holds configuration related for SQL query conditions

Collaborators:
- Config
end note
@enduml
@startuml inline_umlgraph_5.svg
class Config {

}

Config --> ArchiveConfig : Passes archive related configurations
Config --> AuditConfig : Passes audit related configurations
Config --> BatchConfig : Passes batch related configurations
Config --> ConditionConfig : Passes condition related configurations
Config --> KafkaConfig : Passes kafka related configurations

note right of Config
Responsibilities:
- creates the general configuration objects for the program

Collaborators:
- ArchiveConfig
- AuditConfig
- BatchConfig
- ConditionConfig
- KafkaConfig
endnote

note bottom of ArchiveConfig
Responsibilities:
- Stores archive related configurations
endnote

note bottom of AuditConfig
Responsibilities:
- holds configuration related to the audit
endnote

note bottom of BatchConfig
Responsibilities:
- Holds configurations related to the batch
endnote

note bottom of ConditionConfig
Responsibilities:
- holds configuration related for SQL query conditions
endnote

note bottom of KafkaConfig
Responsibilities:
- Holds configurations related to Apache Kafka
endnote
@enduml
@startuml inline_umlgraph_6.svg
class KafkaConfig {

}

KafkaConfig --> Config

note right of KafkaConfig
Responsibilities:
- Holds configurations related to Apache Kafka

Collaborators:
- Config
end note
@enduml
@startuml inline_umlgraph_7.svg
class KafkaOffsetMetricAggregator {
    + name()
    + description()
    + aggregateTaskMetrics()
}

KafkaOffsetMetricAggregator --> TaskMetric
KafkaOffsetMetricAggregator --> CustomMetric

note left of KafkaOffsetMetricAggregator
Responsibilities:
- Aggregates the latest processed Kafka timestamp metric

Collaborators:
- CustomMetric
end note
@enduml
@startuml inline_umlgraph_8.svg
class RecordsPerSecondMetricAggregator {
    + name()
    + description()
    + aggregateTaskMetrics()
}

LatestKafkaTimestampMetricAggregator --> TaskMetric
LatestKafkaTimestampMetricAggregator --> CustomMetric

note left of LatestKafkaTimestampMetricAggregator
Responsibilities:
- Aggregates the latest processed Kafka timestamp metric
- Holds the name and description of the metric

Collaborators:
- CustomMetric
end note
@enduml
@startuml inline_umlgraph_9.svg
class RecordsPerSecondMetricAggregator {
    + name()
    + description()
    + aggregateTaskMetrics()
}

RecordsPerSecondMetricAggregator --> TaskMetric
RecordsPerSecondMetricAggregator --> CustomMetric

note left of RecordsPerSecondMetricAggregator
Responsibilities:
- Aggregates the number of records processed per second metric
- Holds the name and description of the metric

Collaborators:
- CustomMetric
end note
@enduml
@startuml inline_umlgraph_10.svg
class RecordsProcessedMetricAggregator {
    + name()
    + description()
    + aggregateTaskMetrics()
}

RecordsProcessedMetricAggregator --> TaskMetric
RecordsProcessedMetricAggregator --> CustomMetric

note left of RecordsProcessedMetricAggregator
Responsibilities:
- Aggregates the number of records processed metric
- Holds the name and description of the metric

Collaborators:
- CustomMetric
end note
@enduml
