@startuml inline_umlgraph_1.svg
class HBaseBatchSliceCollection {
    + processRange(Offset start, Offset end)
}

HBaseBatchSliceCollection --> HBaseQuery : results source
HBaseBatchSliceCollection --> SynchronizedHourlyResults : syncs results for hour
HBaseBatchSliceCollection --> BatchSizeLimit : limits the results per hour
HBaseBatchSliceCollection --> Config : options for used objects

Collaborators:
- HBaseQuery
- SynchronizedHourlyResults
- BatchSizeLimit
- Config
@enduml
